version: "3"

services:
    go:
        image: golang
        container_name: golang
        volumes: 
            - ".:/app"
        working_dir: "/app"
        tty: true
        command: bash # usando "docker-compose run go"
